#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Error:  Usage: $Pgm [wt|cal|prot] amount(g)"
    exit 0
fi

Pgm=`basename "$0"`
Stat="$1"
Amt=$2

. /.env 2>&1 >/dev/null

CerealDB=cereal.db
TmpF=/tmp/tf.$Pgm

idx=1
while [ $idx -lt 36 ]; do
    cereals $Stat | sed -n "${idx}p" > $TmpF
    sel=`cut -f1 -d$'\t' $TmpF`
    wt0=`cut -f2 -d$'\t' $TmpF`
    cal0=`cut -f3 -d$'\t' $TmpF`
    prot0=`cut -f2 -d$'\t' $TmpF`
    printf "%s\t%3.3f\n" "$sel" `bcx "wt2cp($Amt,$wt0,$cal0,$prot0)" | grep "cal:" | awk '{print $6}'`
    idx=$(( $idx + 1 ))
done | sort -k2,2n -t$'\t'
