#!/bin/bash

DB=cereal-2.db
Pgm=`basename "$0"`
Styp=n

case "$1" in
    code|abbr)
        scol=5
        Styp=''
        ;;
    ''|name)
        scol=1
        Styp=''
        ;;
    weight|wt)
        scol=2
        ;;
    calories|cal)
        scol=3
        ;;
    protein|prot)
        scol=4
        ;;
    *)
        echo "Error: column must be code, name, wt, cal, or prot"
        exit 1
        ;;
esac

while read txt; do
    code=`echo -e "$txt" | cut -f1 -d$'\t'`
    name=`echo -e "$txt" | cut -f2 -d$'\t'`
    wt=`echo -e "$txt" | cut -f3 -d$'\t' | sed 's/g//'`
    cal=`echo -e "$txt" | cut -f4 -d$'\t' | sed 's/c//'`
    prot=`echo -e "$txt" | cut -f5 -d$'\t' | sed 's/p//'`
    printf "%-60s\t%5s\t%5s\t%6s\t%-12s\n" "$name" $wt $cal $prot $code
done < $DB | sort -t$'\t' -k${scol},${scol}$Styp
