#!/usr/bin/python3
"""
Acting as a python programmer, write a script to split a text file into a list of  words using spaces, commas, and close parentheses for delimiters. Check the command line to see if a valid filename of an existing file has been supplied. If no filename has been specified, the script should prompt for the name of the text file.   Delete from the list any words that include characters other than numbers and the lower case character 'c'.  Print the list on one line. Delete the lower case character 'c' and any other non-numeric characters from each entry, add them all together, and print the sum prefixed with the string "Total calories: "
"""

import os
import sys
import re

def main():
    # Check if a filename has been specified on the command line.
    if len(sys.argv) == 2:
        filename = sys.argv[1]
    else:
        # Prompt for the filename.
        filename = input("Enter the name of the text file: ")

    # Open the file in read mode.
    with open(filename, "r") as f:
        data = f.read()

    # Split the data into a list of words.
    words = re.split("[ ,)]|\)", data)

    # Remove any words that contain characters other than numbers and the lowercase character 'c'.
    valid_words = []
    for word in words:
        if re.match("[0-9c]+", word):
            valid_words.append(word)

    # Print the list of valid words on one line.
    print(" ".join(valid_words))

    # Remove the lowercase character 'c' and any other non-numeric characters from each entry, and add them all together.
    calories = 0
    for word in valid_words:
        calories += int(word.replace("c", ""))

    # Print the total calories.
    print("Total calories:", calories)

if __name__ == "__main__":
    main()
