#!/usr/bin/python3

import sys
import re

def delete_elements(file_name):
  with open(file_name, 'r') as f:
    lines = f.readlines()

  new_words = []
  for line in lines:
    words = re.split(', | |\(|\)', line)
    for word in words:
      if word.endswith('g'):
        if all(x.isdigit() for x in word[:-1]):
          new_words.append(word[:-1])

  total_weight = sum(int(word.strip('g')) for word in new_words)

  with open(file_name + '.out', 'w') as f:
    f.write("Weights: " + ' '.join(new_words))
    f.write('\n')
    f.write("Total weight: " + str(total_weight) + '\n')

def main():
  file_name = sys.argv[1]
  delete_elements(file_name)

  # Repeat the file processing substituting the character 'c'

  with open(file_name, 'r') as f:
    lines = f.readlines()

  new_words = []
  for line in lines:
    words = re.split(', | |\(|\)', line)
    for word in words:
      if word.endswith('c'):
        if all(x.isdigit() for x in word[:-1]):
          new_words.append(word[:-1])

  total_calories = sum(int(word.strip('c')) for word in new_words)

  with open(file_name + '.out', 'a') as f:
    f.write('\n')
    f.write("Calories: " + ' '.join(new_words))
    f.write('\n')
    f.write("Total calories: " + str(total_calories) + '\n')

if __name__ == '__main__':
  main()
